spring:
  cloud:
    gateway:
      routes:
      - id: authserver
        uri: lb://authserver
        predicates:
        - Path=/authenticate
        - Path=/product
        - Path=/cart
        - Path=/order