spring:
  cloud:
    gateway:
      routes:
      - id: authserver
        uri: lb://authserver
        predicates:
        - Path=/authenticate
      - id: productmspoc
        uri: lb://productmspoc
        predicates:
        - Path=/product/**
      - id: cartmspoc
        uri: lb://cartmspoc
        predicates:
        - Path=/cart/**
      - id: ordermspoc
        uri: lb://ordermspoc
        predicates:
        - Path=/order
      - id: auditmspoc
        uri: lb://auditmspoc
        predicates:
        - Path=/audit/**
        
      