spring:
  cloud:
    gateway:
      routes:
      - id: authserver
        uri: lb://authserver
        predicates:
        - Path=/authenticate
      - id: productmspoc
        uri: lb://productmspoc
        predicates:
        - Path=/product
      